version: 0.2

phases:
  install:
    commands:
      - pip3 install --user --upgrade anchorecli
  pre_build:
    commands:
      - echo logging into Amazon ECR
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin 377877851685.dkr.ecr.eu-west-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEDBUILD_RESOLVED_SOURCE_VERSION  |  cut -c 1-7 )
      - IMAGE_TAG=build-$(echo $CODEDBUILD_BUILD_ID)

  build:
    commands:
      - echo Build started on  `date`
      - echo Building the Docker image…
      - REPOSITORY_URI=377877851685.dkr.ecr.eu-west-1.amazonaws.com/anchore-codebuildproject
      - docker build -t REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on  `date`
      - anchore-cli image add $REPOSITORY_URI:latest
      - echo "Waiting for image to finish analysis"
      - anchore-cli image wait $REPOSITORY_URI:latest
      - echo "Analysis complete"
      - if [ "$ANCHORE_FAIL_ON_POLICY" = "true" ] ; then anchore-cli evaluate check $REPOSITORY_URI:latest  ; fi
      - echo "Pushing the docker images”     
      - docker push $REPOSITORY_URI:latest
